name       : dnscrypt-proxy
version    : 1.8.1
release    : 1
source     :
    - https://github.com/jedisct1/dnscrypt-proxy/archive/1.8.1.tar.gz : 2e392b4b02ece2c60d1bcb6bab658cfcea3171030f9a982b5e9ed66543d11103
license    : MIT
component  : network.utils
summary    : A tool for securing communications between a client and a DNS resolver
description: |
    A tool for securing communications between a client and a DNS resolver
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libsodium)
setup      : |
    sed -i "s|local/bin|bin|" dnscrypt-proxy.service
    sed -i "s|/usr/local||" dnscrypt-proxy.service
    %reconfigure --with-systemd
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 dnscrypt-proxy.service $installdir/usr/lib64/systemd/system/dnscrypt-proxy.service
    install -D -m 00644 dnscrypt-proxy.socket $installdir/usr/lib64/systemd/system/dnscrypt-proxy.socket
patterns   :
    - devel :
        - /usr/lib64/dnscrypt-proxy/