name       : dnscrypt-proxy
version    : 2.0.45
release    : 7
source     :
    - https://github.com/DNSCrypt/dnscrypt-proxy/archive/2.0.45.tar.gz : f7aac28c6a60404683d436072b89d18ed3bb309f8d8a95c8e87ad250da190821
license    : ISC
extract    : no
component  : network.utils
summary    : A flexible DNS proxy, with support for encrypted DNS protocols.
description: |
    A flexible DNS proxy, with support for modern encrypted DNS protocols such as DNSCrypt v2 and DNS-over-HTTPS.
builddeps  :
    - golang
setup      : |
    mkdir root
    tar -xf $sources/$version.tar.gz -C root
    pushd root
    mv dnscrypt-proxy* src
    popd
    pushd root/src
    %patch -p1 < $pkgfiles/0001-Patch-to-fall-back-to-fixed-stateless-dir.patch
    popd
build      : |
    export GOPATH="${workdir}"
    export GOOS=linux
    export GOARCH=amd64
    cd src/dnscrypt-proxy
    go build -ldflags="-s -w" -o $GOPATH/linux-amd64/dnscrypt-proxy
    cp example-dnscrypt-proxy.toml $GOPATH/linux-amd64/
install    : |
    install -Dm00755 linux-amd64/dnscrypt-proxy $installdir/usr/bin/dnscrypt-proxy
    install -Dm00644 linux-amd64/example-dnscrypt-proxy.toml $installdir/usr/share/defaults/dnscrypt-proxy/dnscrypt-proxy.toml
    install -Dm00644 $pkgfiles/dnscrypt-proxy.service $installdir/%libdir%/systemd/system/dnscrypt-proxy.service
