name       : dnscrypt-proxy
version    : 2.0.19
release    : 4
source     :
    - https://github.com/jedisct1/dnscrypt-proxy/archive/2.0.19.tar.gz : 98b05aec5187cd4c2aea910d7ea7facd5ad57c0cbfa07401868647764d5c2896
license    : ISC
extract    : no
component  : network.utils
summary    : A flexible DNS proxy, with support for encrypted DNS protocols.
description: |
    A flexible DNS proxy, with support for modern encrypted DNS protocols such as DNSCrypt v2 and DNS-over-HTTPS.
builddeps  :
    - golang
setup      : |
    mkdir root
    tar -xf $sources/$version.tar.gz -C root
    cd root &&
    rename dnscrypt-proxy-$version src dnscrypt-proxy-$version
build      : "export GOPATH=\"${workdir}\"\nexport GOOS=linux \nexport GOARCH=amd64\ncd src/dnscrypt-proxy\ngo build -ldflags=\"-s -w\" -o $GOPATH/linux-amd64/dnscrypt-proxy\ncp example-dnscrypt-proxy.toml\
    \ $GOPATH/linux-amd64/\n"
install    : |
    install -Dm00755 linux-amd64/dnscrypt-proxy $installdir/usr/bin/dnscrypt-proxy
    install -Dm00644 linux-amd64/example-dnscrypt-proxy.toml $installdir/etc/dnscrypt-proxy.toml
    install -Dm00644 $pkgfiles/dnscrypt-proxy.service $installdir/etc/systemd/system/dnscrypt-proxy.service
