name       : dnscrypt-proxy
version    : 2.0.16
release    : 3
source     :
    - https://github.com/jedisct1/dnscrypt-proxy/archive/2.0.16.tar.gz : 7ff4cb7890fdf6b1b54ec4a9ef9f8ba5e71bcaff8522f324ef6ecc739ce95e5e
license    : ISC
extract    : no
component  : network.utils
summary    : A flexible DNS proxy, with support for encrypted DNS protocols.
description: |
    A flexible DNS proxy, with support for modern encrypted DNS protocols such as DNSCrypt v2 and DNS-over-HTTPS.
builddeps  :
    - golang
setup      : |
    mkdir root
    tar -xf $sources/$version.tar.gz -C root
    cd root &&
    rename dnscrypt-proxy-$version src dnscrypt-proxy-$version
build      : |
    export GOPATH="${workdir}"
    export GOOS=linux 
    export GOARCH=amd64
    cd src/dnscrypt-proxy
    go build -ldflags="-s -w" -o $GOPATH/linux-amd64/dnscrypt-proxy
    cp example-dnscrypt-proxy.toml $GOPATH/linux-amd64/
install    : |
    install -Dm00755 linux-amd64/dnscrypt-proxy $installdir/usr/bin/dnscrypt-proxy
    install -Dm00644 linux-amd64/example-dnscrypt-proxy.toml $installdir/etc/dnscrypt-proxy.toml
    install -Dm00644 $pkgfiles/dnscrypt-proxy.service $installdir/etc/systemd/system/dnscrypt-proxy.service
