name       : dnscrypt-proxy
version    : 1.8.1
release    : 2
source     :
    - https://launchpad.net/ubuntu/+archive/primary/+files/dnscrypt-proxy_1.8.1.orig.tar.gz : 5cad1d2357852dc16957085e7a9b32384fb9b95c609e185b7ae1a3959fc13769
license    : MIT
component  : network.utils
summary    : A tool for securing communications between a client and a DNS resolver
description: |
    A tool for securing communications between a client and a DNS resolver
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libsodium)
setup      : |
    sed -i "s|local/bin|bin|" dnscrypt-proxy.service
    sed -i "s|/usr/local||" dnscrypt-proxy.service
    %reconfigure --with-systemd
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 dnscrypt-proxy.service $installdir/usr/lib64/systemd/system/dnscrypt-proxy.service
    install -D -m 00644 dnscrypt-proxy.socket $installdir/usr/lib64/systemd/system/dnscrypt-proxy.socket
patterns   :
    - devel :
        - /usr/lib64/dnscrypt-proxy/
